# Generated by Django 5.0.2 on 2024-02-22 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_book_app', '0003_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='year_published',
            field=models.IntegerField(),
        ),
    ]
