# Generated by Django 5.0.2 on 2024-02-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_book_app', '0009_uploadedfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
    ]
